
var SqlList ={
    "USERINFO_SQL"                     : "Select PROFILE_ID,USER_LOGIN_ID,USER_PWD,USER_TYPE,USER_STATUS from USER_LOGIN_INFO",
    "USERBASICINFO_SQL"                : "Select PROFILE_ID,ISACOMMUNITY,USER_FIRST_NAME,USER_LAST_NAME from USER_BASIC_INFO",
    "NEW_USER_BASIC_SQL"               : "INSERT INTO USER_BASIC_INFO VALUES(:PROFILE_ID,:ISACOMMUNITY,:USER_FIRST_NAME,:USER_LAST_NAME,:USER_EMAIL_ID,:USER_MOBILE_ID,:CREATION_DATE,:CREATION_TIME );",
    "NEW_USER_BASIC_IN_DEPTH_SQL"      : "INSERT INTO USER_BASIC_INFO_INDEPTH VALUES(:PROFILE_ID,:PROFILE_DESC,:USER_GENDER,:USER_BIRTHDAY,:USER_MARTIAL_STATUS,:USER_SEXUAL_ORIENTATION,:USER_OCCUPATION,:USER_COUNTRY,:USER_STATE,:USER_PLACE,:CREATION_DATE,:CREATION_TIME );",
    "NEW_COMMUNITY_BASIC_IN_DEPTH_SQL" : "INSERT INTO COMMUNITY_BASIC_INFO_INDEPTH VALUES(:COMMUNITY_PROFILE_ID,:COMMUNITY_STATUS,:COMMUNITY_AUTHOR_ID,:COMMUNITY_NAME,:COMMUNITY_DESCRIPTION,:COMMUNITY_COUNTRY,:COMMUNITY_PLACE,:CREATION_DATE,:CREATION_TIME );",
    "NEW_USER_LOGIN_SQL"               : "INSERT INTO USER_LOGIN_INFO VALUES(:PROFILE_ID,:USER_LOGIN_ID,:USER_PWD,:USER_TYPE,:USER_STATUS,:CREATION_DATE,:CREATION_TIME );",
    "USER_LOGIN_BASIC_INFO_SQL"        : "SELECT * FROM USER_BASIC_INFO ",
    "NEW_FORGOT_PASSWORD_SQL"          : "INSERT INTO forgot_password VALUES(:USER_LOGIN_ID,:AUTH_KEY,:EXPIRARY_DATE,:EXPIRARY_TIME );",
    "GET_FORGOT_PASSWORD_DETAILS_SQL"  : "Select USER_LOGIN_ID,AUTH_KEY,EXPIRARY_DATE,EXPIRARY_TIME from forgot_password",
    "NEW_PASSWORD_SETUP_SQL"           : "Update USER_LOGIN_INFO SET USER_PWD=:USER_PWD",
    "FORGOT_PASSWORD_HASH_SQL"         : "SELECT USER_LOGIN_ID,AUTH_KEY,EXPIRARY_DATE,EXPIRARY_TIME FROM forgot_password",
};

export default SqlList;


